import os

# URLS
FRONTEND_URL = os.environ.get('FRONTEND_URL')
MONGO_HOST = os.environ.get('MONGO_HOST')
AUTH_HOST = f"http://{os.environ.get('AUTH_HOST')}:5000"
PAYMENT_HOST = f"http://{os.environ.get('PAYMENT_HOST')}:5000"
NOTIFICATION_HOST = f"http://{os.environ.get('NOTIFICATION_HOST')}:5000"

# notifications
ZOLUTIA_PHONE = os.environ.get('ZOLUTIA_PHONE')
CONFIRMATION_TEMPLATE = os.environ.get('CONFIRMATION_TEMPLATE')
ORDER_PHARMACY_TEMPLATE = os.environ.get('ORDER_PHARMACY_TEMPLATE')
ORDER_CLIENT_TEMPLATE = os.environ.get('ORDER_CLIENT_TEMPLATE')
SHIPPING_CLIENT_TEMPLATE = os.environ.get('SHIPPING_CLIENT_TEMPLATE')
WELCOME_TEMPLATE = os.environ.get('WELCOME_TEMPLATE')
RESET_PASSWORD_TEMPLATE = os.environ.get('RESET_PASSWORD_TEMPLATE')
SUBSCRIPTION_CLIENT_TEMPLATE = os.environ.get('SUBSCRIPTION_CLIENT_TEMPLATE')
AWS_ACCESS_KEY = os.environ['AWS_ACCESS_KEY']
AWS_SECRET_KEY = os.environ['AWS_SECRET_KEY']
AWS_BUCKET_NAME = os.environ['AWS_BUCKET_NAME']
